Make shim work even if python3-venv isn't installed

diff --git a/audius-cli b/audius-cli
--- a/audius-cli
+++ b/audius-cli
@@ -6,11 +6,18 @@ set -e
 cd "$(dirname "$(readlink -f "$0")")"
 
 # create venv if it doesn't already exist
-if ! [ -d .venv ]; then
-  python3 -m venv .venv
+# Note: venv creation may fail if package python3-venv is not installed,
+# in which case a message will be displayed each time reminding the user.
+if [ -f .venv/bin/activate ] || python3 -m venv .venv; then
+  source .venv/bin/activate
 fi
 
-source .venv/bin/activate
-python3 -m pip install -r requirements.txt
+install_outfile="$(mktemp)"
+
+if ! python3 -m pip install -r requirements.txt &> "$install_outfile"; then
+  cat "$install_outfile"
+fi
+
+rm "$install_outfile"
 
 python3 audius-cli.py "$@"
